apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-lob-https-redirect
  annotations:
    policies.kyverno.io/title: Auto-Generate HTTPS Redirect
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Namespace, HTTPRoute
    policies.kyverno.io/description: >-
      Automatically creates an HTTPRoute to redirect HTTP to HTTPS for LOB gateways.
spec:
  generateExisting: true
  rules:
    - name: create-https-redirect
      match:
        any:
          - resources:
              kinds:
                - Namespace
              selector:
                matchExpressions:
                  - key: system
                    operator: DoesNotExist
      generate:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        name: "{{ request.object.metadata.name }}-https-redirect"
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        data:
          metadata:
            labels:
              managed-by: kyverno
              lob-namespace: "{{ request.object.metadata.name }}"
              app.kubernetes.io/created-by: platform-team
            annotations:
              kyverno.io/generated-by: generate-lob-https-redirect
          spec:
            parentRefs:
              - name: "{{ request.object.metadata.name }}-gateway"
                namespace: "{{ request.object.metadata.name }}"
                sectionName: http
            hostnames:
              - "*.{{ request.object.metadata.name }}.example.com"
            rules:
              - filters:
                  - type: RequestRedirect
                    requestRedirect:
                      scheme: https
                      statusCode: 301
