apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-lob-traffic-policy
  annotations:
    policies.kyverno.io/title: Auto-Generate LOB Traffic Policy
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Namespace, ClientTrafficPolicy
    policies.kyverno.io/description: >-
      Automatically creates a ClientTrafficPolicy for each LOB gateway with standard settings.
spec:
  generateExisting: true
  rules:
    - name: create-traffic-policy
      match:
        any:
          - resources:
              kinds:
                - Namespace
              selector:
                matchExpressions:
                  - key: system
                    operator: DoesNotExist
      generate:
        apiVersion: gateway.envoyproxy.io/v1alpha1
        kind: ClientTrafficPolicy
        name: "{{ request.object.metadata.name }}-traffic"
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        data:
          metadata:
            labels:
              managed-by: kyverno
              lob-namespace: "{{ request.object.metadata.name }}"
              app.kubernetes.io/created-by: platform-team
            annotations:
              kyverno.io/generated-by: generate-lob-traffic-policy
          spec:
            targetRef:
              group: gateway.networking.k8s.io
              kind: Gateway
              name: "{{ request.object.metadata.name }}-gateway"
            connection:
              bufferLimit: 32KiB
              connectionLimit:
                value: 5000
                closeDelay: 5s
            timeout:
              http:
                requestReceivedTimeout: 60s
                idleTimeout: 300s
            http2:
              maxConcurrentStreams: 100
            clientIPDetection:
              xForwardedFor:
                numTrustedHops: 1
